### PR TITLE
Fix for external source

### PR DESCRIPTION
**Pull request by Minstel**

### CODE REVIEW

**Review by jasny — CHANGES_REQUESTED** [review]
Let's shy away from a generic js file.

**Comment by Minstel** [comment]
Currently `extendExternalUrl` function from this file is needed in `ractive-legalform.js` and in `legalform.js`. So where is the best place to put it?

**Comment by jasny** [comment]
@Minstel I'm picking this up.

**Comment by jasny** [comment]
screenshot-localhost-8008 2017-03-09 11-18-41

**Review by jasny — APPROVED** [review]

**Pull request merged**
